//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

pub use super::menu::Entity as Menu;
pub use super::role::Entity as Role;
pub use super::role_menu::Entity as RoleMenu;
pub use super::user::Entity as User;
pub use super::user_role::Entity as UserRole;
